### ISSUE TITLE
How do you bypass the layer error?

### ISSUE THREAD

**Issue by luorix1** [sxzrt/Illustration-of-the-PersonX-dataset#11]
First of all, thank you for publishing this on Github. It was a great boost for ML researchers like me who are unfamiliar with Unity when working on synthetic data.

```
A game object can only be in one layer. The layer needs to be in the range [0...31]
```

I understand that I need to assign my game objects to a layer via Edit > Project Settings > Tags and Layers > Layers and that it should be under "Role".
However, I am unsure how to add a Role layer so that this error stops occurring.
Any help would be much appreciated.

**Comment by luorix1** [comment]
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/63445340/145528121-877c8274-d369-4417-a6a5-e4b764811ef4.png">

**Comment by luorix1** [comment]
It seems in ChangeLayer() in LoadRole.cs, the transforms.Length exceeds 31 (causing an error)
<img width="1878" alt="image" src="https://user-images.githubusercontent.com/63445340/145529458-68a332dd-cc15-4535-b2b9-4cd7dd24185f.png">

**Comment by luorix1** [comment]
Sorry, it works now. :)

**Comment by sxzrt** [comment]
Thanks for your questions, and hope PersonX is helpful to you. ;)
