### ISSUE TITLE
Could you please share the scenes used in your paper?

### ISSUE THREAD

**Issue by Alan-Paul** [sxzrt/Illustration-of-the-PersonX-dataset#2]

**Comment by sxzrt** [comment]
Hi, the scenes we used are bought from the store, so we cannot release it directly on GitHub.  You can email me, and I can send it to you for academic purposes.

**Comment by zmdjttgxs** [comment]
Could you please share the scenes used in your paper?I’ve sent the e-mail but I haven't got the respond yet.

**Comment by sxzrt** [comment]
Hi, I have replied all the emails. I think you might have received it. If not, please send me another email so that I can get your email address and reply.

**Comment by zmdjttgxs** [comment]
> 
> 
> Hi, I have replied all the emails. I think you might have received it. If not, please send me another email so that I can get your email address and reply.

I got the email just now.Thank you so much!
