### ISSUE TITLE
How are the person models generated?

### ISSUE THREAD

**Issue by tyz1994** [sxzrt/Illustration-of-the-PersonX-dataset#5]
Thanks for your great work! I have some questions about person models. 

I notice that the 1,266 person models are hand-crafted. May I ask which software or tool you use? What should I do if I want to generate more models? 

Many thanks!

**Comment by sxzrt** [comment]
3Dmax and Blender or other 3D model building models as well as photoshop.

**Comment by tyz1994** [comment]
Thank you for your information.
