### ISSUE TITLE
How to let the person model walk?

### ISSUE THREAD

**Issue by realgump** [sxzrt/Illustration-of-the-PersonX-dataset#8]
I have drag the game_manager_demo into the scene as the readme doc, then I draged the person model A1 from resources to the person position. I noticed there is a animation companient in inspector of A1. However, after I opened the animation and clipped the start botton, the person model in the game window did be walking, but she didn't move -- just walk in the save position. I wonder how can I make the person model walk and move.

**Comment by sxzrt** [comment]
Hi,

Please check if you have set values of Random Position for PeoplePosition under Game_Manager. 


![image](https://user-images.githubusercontent.com/19248415/94559685-f5671e00-02a4-11eb-88ac-951c012ee862.png)

**Comment by realgump** [comment]
Thanks for your reply. I tried to follow the gif in Readme doc again, delete the default camera, and drag the demo into the hierachy tab. 

<img width="1286" alt="微信图片_20200930232052" src="https://user-images.githubusercontent.com/37771769/94705448-a6d48500-0373-11eb-9fa0-426b5b77ce2f.png">


I firstly set the values of RandomPosition as default, and then tried the values in your screenshot. Then I click the start button, but nothing happened in the window. I have shown my operation in above screenshot.

I am a green hand of Unity and I will be very appreciate if you could point out my mistakes.

**Comment by sxzrt** [comment]
Hi, 

Is there an error warning when running? 

From your screenshot, no person appearances in your camera, so I think the Game_manager_demo does not work in your project. Please check if the id of the first 3D model in Resource is 0.

**Comment by realgump** [comment]
Thanks, the reason is because the first id in Resource is not 1, the code works well after rename the id.
